### ISSUE TITLE
LoadSaveFile loop logic

### ISSUE THREAD

**Issue by CScavone96** [forensic63j/SwiftSands#1]
LoadSaveFile currently loops based on the number of sprites loaded. Would make more sense to loop based on number of Characters saved to file. Example, if all Characters are loaded from one sprite sheet the original implementation will fail. Why does LoadSaveFile even load textures?

**Comment by bxs9775** [comment]
I adjusted the way the program iterates. But we need the character's textures to draw them, and it would be problematic searching through the character list to find them.
