### ISSUE TITLE
Valid Tiles Problems

### ISSUE THREAD

**Issue by CScavone96** [forensic63j/SwiftSands#11]
I don't know what exactly the problem is but this image should illustrate part of the problem.

![validtiles](https://cloud.githubusercontent.com/assets/7351705/7102991/71543888-e062-11e4-81ac-070f8e459741.png)

Apparently the player can only move one tile downwards but 3(4?) tiles upwards.

**Comment by bxs9775** [comment]
Were you panning the camera?

**Comment by bxs9775** [comment]
I think it is likely a result of Combat methods using the wrong coordinate system. I'll try taking a look after I work on math and psych.

**Comment by bxs9775** [comment]
Not sure what is going on, when you pan the wrong tiles end up highlighted, or no tiles are highlighted at all or tiles are highlighted but vanish under the mouse pointer.

I do not know if there is one problem in the code are many. I found a case where the validTile array is right but the tinted tiles were moved over.
![image](https://cloud.githubusercontent.com/assets/11140195/7107147/ba4bbacc-e128-11e4-8b6a-86092839d058.png)

**Comment by bxs9775** [comment]
In terms of the problem you found I have figured out what is going on and can solve it, but there are other related issues we need to look at.

**Comment by bxs9775** [comment]
Well movement is looking good but the targeting squares tiles are moving with the camera.

**Comment by CScavone96** [comment]
Tile tints should be working correctly. Check newest commit and confirm. If you agree that they are working as you would expect feel free to close this issue.

**Comment by bxs9775** [comment]
I think things are looking good. We'll reopen this issue if issues return.
