### ISSUE TITLE
If Enemy has No Valid Moves

### ISSUE THREAD

**Issue by CScavone96** [forensic63j/SwiftSands#16]
If the enemy is cornered by the players and has no moves then he will not take his turn.

**Comment by bxs9775** [comment]
Ok, I 'll take a look. I will have to add a line so that the enemy checks if it can move.

**Comment by bxs9775** [comment]
I just made a commit that should fix the problem, and seems to work on my computer. Enemy now checks if there is anywhere to move, and if not sets its moves left to 0. I am closing this issue, but feel free to reopen it if there any more problems.
