### ISSUE TITLE
Characters with same speed

### ISSUE THREAD

**Issue by CScavone96** [forensic63j/SwiftSands#5]
If multiple characters have the same speed will they move on the same turn? If so both combat and movement will have to support selecting a player. Party class now stores a SelectedPlayer property to do so.

**Comment by bxs9775** [comment]
I wondered what the SelectedPlayer Method is about. No characters with the same speed do not move on the same turn, in the case of a tie the player who comes first in the Party goes first.

**Comment by CScavone96** [comment]
Why not let them move at the same time?

**Comment by forensic63j** [comment]
It'd be easier to have them go one at a time I'd think

**Comment by CScavone96** [comment]
But we have the ability to select players now and move them independently.

**Comment by bxs9775** [comment]
I think the combat list system as it is works fine. Allowing characters to move at the same time, but I would have to change the way Combat handles whose turn it is, and I do not feel characters being able to go at the same time is entirely necessary for the program. 
edit: There would be more work involved setting up the mouse click functionality than the methods you added.
