### ISSUE TITLE
Tile Recoloration for Combat

### ISSUE THREAD

**Issue by bxs9775** [forensic63j/SwiftSands#7]
Combat calculates where a character can move or attack using an array of booleans where 'false' is a valid option (this is due to the initial value of Boolean being true). Is there a way to make it so The valid tiles change color so the player knows which tiles are valid?

**Comment by CScavone96** [comment]
This is definitely possible. I will look into adding a method that takes coordinates and tints tiles based on it.

**Comment by bxs9775** [comment]
Ok, thank you.

**Comment by CScavone96** [comment]
Added a method called TintTile. It takes a Vector2 and a color and should tint a tile.

edit: tested it works gr8
