### ISSUE TITLE
Strange Movement/Combat Interaction

### ISSUE THREAD

**Issue by bxs9775** [forensic63j/SwiftSands#8]
The way movement is currently coded allows player characters to move when they should not be moving.

**Comment by CScavone96** [comment]
I added collision checks to the character's move method. The move method also now returns a bool based on if the move was successful or not.

**Comment by bxs9775** [comment]
Actually, I resolved the problem in the commit before. Also, make sure someone is fine with you changing their code before you do so. Your changes mainly hindered movement in combat.

**Comment by CScavone96** [comment]
No you didnt. Collision didn't work. Movement didn't work if the camera panned and more. I made fixes and improvements to mostly movement, my code, and could appreciate if you would adapt and use the systems Im setting up.

**Comment by CScavone96** [comment]
When I find time Ill sync back to your version and double check that movement had glitches in both combat and localmap and that my code didn't break anything.

**Comment by CScavone96** [comment]
Also, if you open issues and then resolve them comment saying how you resolved them and close the issue please.

**Comment by bxs9775** [comment]
I am sorry, I should of let you know what I was working on, and I will try to be more adaptable. At the same time, can you try to keep in contact more, and if you see problems that are on my end contact me? Problems in the code should be negotiated between us. However, it feels sometimes I do not know what is going on in my own code because you made some change in the middle of the night without my knowledge.

**Comment by bxs9775** [comment]
One problem I have with the current implementation is I think the selection movement method used by local map should be inactive during combat, and I want the player to be able to move the character without the character being selected, as there should only be one character available for the player to move at any one time anyways.

**Comment by CScavone96** [comment]
Games in the genre frequently let you select a character to obtain information about them. Say to see how much health an enemy has left you could select them and then it will provide info. Thats what I would like to imlement hence I want to leave it in.

**Comment by CScavone96** [comment]
Then we could use it for targeting too. After clicking attack you can select an enemy to attack them with similar logic.

**Comment by bxs9775** [comment]
Ok, that makes sense.

**Comment by CScavone96** [comment]
Awesome, thanks. We could have a panel along the bottom of the Combat state that has information about selected characters and the buttons for combat.

**Comment by bxs9775** [comment]
I'll work on it after I get some of this code working.

**Comment by bxs9775** [comment]
I have not looked at the selection methods you are suggesting, but I have working move and attack methods. What you are suggesting may help, but selection must be able to select enemies and not just party members.

**Comment by CScavone96** [comment]
I will add that functionality.

**Comment by bxs9775** [comment]
Ok, I'll work on the panel when I get time.

**Comment by bxs9775** [comment]
Until then this issue should remain open.

**Comment by bxs9775** [comment]
Ok, the panel is finished.
