### ISSUE TITLE
Moveleft boolean

### ISSUE THREAD

**Issue by CScavone96** [forensic63j/SwiftSands#9]
Instead of moveleft being a boolean I would recommend you change it to a integer based on the number of moves a character has. Then when they make a move just decrement moveleft until it is zero and they can no longer make moves.

**Comment by bxs9775** [comment]
Maybe, seems simpler for the player just to make a single move.

**Comment by CScavone96** [comment]
Do you want to make a simple game or do you want to make a good game?

**Comment by bxs9775** [comment]
Either way works, though I was thinking to handle movement similar to D&D (aka you have one move action where you can move up to your move speed). Though if you are dead set on me changing this system I could.

**Comment by CScavone96** [comment]
Oh okay that is another solution then. I thought you meant we were going to let players only ever move one space per turn. Ill consider the two options and get back to you.

**Comment by CScavone96** [comment]
I could make it so the move method allows a character to move up to thier moverange in one turn. However this would introduce a variety of problems. First what if they move only half their movement range? I would have to introduce new variables to the character about how many moves they have left. What if they choose a tile within thier moverange but is unreachable due to collisions. Plus moverange is only going to be needed in the combat state anyway. I would recommend my original suggestion of simply changing the moveleft variable to an integer that is decremented when a succesful move is made.

**Comment by bxs9775** [comment]
ValidMovements is designed to figure out what tiles a player can reach with there current number of moves, and is set up to factor in tiles unreachable due to collisions unless it has been changed allot. Although, it seems to have some trouble.

**Comment by bxs9775** [comment]
Combat is already tracking movement and is designed to get the ValidTiles to move to and pass character or whatever handles the movement the destination square.

**Comment by CScavone96** [comment]
So, if ValidMovements is still having trouble it would just be easier to check if a move was succesful and decrement a movesLeft int.

**Comment by bxs9775** [comment]
Well, I think I have been passing in the wrong starting x and y parameters, so we will see if it works now.

**Comment by bxs9775** [comment]
ValidMovement works now.

**Comment by CScavone96** [comment]
I went ahead and made moveLeft into and integer called movesLeft. 

I know you said to consult with you but before you get angry or anything read through my changes to the valid tile methods and combat. Then actually try combat, it functions and feels a lot better than it did before.

**Comment by bxs9775** [comment]
It looks fine. I wish you would talk to me more instead of making decisions for me, though.
